"""
Core data models for the tutoring agent system.

This module defines the fundamental data structures used across all components
of the STEM tutoring system.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Union
from enum import Enum
from datetime import datetime


class Difficulty(Enum):
    """Problem difficulty levels."""
    BEGINNER = "beginner"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


class Subject(Enum):
    """Supported STEM subjects."""
    STATICS = "statics"
    CIRCUIT_ANALYSIS = "circuit_analysis"


class ErrorSeverity(Enum):
    """Severity levels for detected misconceptions."""
    MINOR = "minor"
    MODERATE = "moderate"
    CRITICAL = "critical"  # Red zone errors


class QuestionType(Enum):
    """Types of Socratic questions."""
    CLARIFICATION = "clarification"
    ASSUMPTION_CHALLENGE = "assumption_challenge"
    CONCEPTUAL = "conceptual"
    CALCULATION_CHECK = "calculation_check"
    VISUAL_AID = "visual_aid"


@dataclass
class ProblemInstance:
    """Represents a structured problem that the tutoring agent can work with."""
    
    id: str
    subject: Subject
    topic: str
    difficulty: Difficulty
    description: str
    metadata: Dict[str, Any] = field(default_factory=dict)
    known_misconceptions: List[str] = field(default_factory=list)
    expected_concepts: List[str] = field(default_factory=list)
    visual_hints: List[str] = field(default_factory=list)
    
    def __post_init__(self):
        if isinstance(self.subject, str):
            self.subject = Subject(self.subject)
        if isinstance(self.difficulty, str):
            self.difficulty = Difficulty(self.difficulty)


@dataclass
class Misconception:
    """Represents a detected conceptual error or misconception."""
    
    id: str
    description: str
    severity: ErrorSeverity
    detected_patterns: List[str] = field(default_factory=list)
    related_concepts: List[str] = field(default_factory=list)
    remediation_strategies: List[str] = field(default_factory=list)
    confidence: float = 0.0  # 0.0 to 1.0
    
    def __post_init__(self):
        if isinstance(self.severity, str):
            self.severity = ErrorSeverity(self.severity)


@dataclass
class SocraticQuestion:
    """Represents a Socratic question generated by the engine."""
    
    id: str
    question_text: str
    question_type: QuestionType
    target_concept: str
    follow_up_questions: List[str] = field(default_factory=list)
    expected_insights: List[str] = field(default_factory=list)
    difficulty_level: Difficulty = Difficulty.INTERMEDIATE
    
    def __post_init__(self):
        if isinstance(self.question_type, str):
            self.question_type = QuestionType(self.question_type)
        if isinstance(self.difficulty_level, str):
            self.difficulty_level = Difficulty(self.difficulty_level)


@dataclass
class VisualSuggestion:
    """Represents a visual aid or diagram suggestion."""
    
    id: str
    title: str
    description: str
    visual_type: str  # "free_body_diagram", "circuit_schematic", etc.
    elements: List[Dict[str, Any]] = field(default_factory=list)
    hints: List[str] = field(default_factory=list)
    is_interactive: bool = False


@dataclass
class StudentResponse:
    """Represents a student's response to a question or problem."""
    
    text: str
    mathematical_expressions: List[str] = field(default_factory=list)
    sketches: List[str] = field(default_factory=list)  # File paths or data
    confidence_indicator: Optional[str] = None  # "unsure", "confident", etc.
    timestamp: datetime = field(default_factory=datetime.now)


@dataclass
class DialogState:
    """Tracks the current state of the tutoring conversation."""
    
    session_id: str
    problem_instance: ProblemInstance
    current_question: Optional[SocraticQuestion] = None
    conversation_history: List[Dict[str, Any]] = field(default_factory=list)
    detected_misconceptions: List[Misconception] = field(default_factory=list)
    resolved_concepts: List[str] = field(default_factory=list)
    pending_concepts: List[str] = field(default_factory=list)
    visual_suggestions_made: List[VisualSuggestion] = field(default_factory=list)
    session_start_time: datetime = field(default_factory=datetime.now)
    last_activity: datetime = field(default_factory=datetime.now)
    
    def add_interaction(self, student_input: str, agent_response: Dict[str, Any]):
        """Add a new interaction to the conversation history."""
        self.conversation_history.append({
            "timestamp": datetime.now(),
            "student_input": student_input,
            "agent_response": agent_response
        })
        self.last_activity = datetime.now()


@dataclass
class TutoringSession:
    """Represents an active tutoring session."""
    
    session_id: str
    dialog_state: DialogState
    is_active: bool = True
    session_metadata: Dict[str, Any] = field(default_factory=dict)
    
    def end_session(self):
        """Mark the session as completed."""
        self.is_active = False
        self.session_metadata["end_time"] = datetime.now()


@dataclass
class AgentResponse:
    """Structured response from the tutoring agent."""
    
    response_type: str  # "question", "visual_suggestion", "clarification", etc.
    content: Union[str, SocraticQuestion, VisualSuggestion]
    detected_misconceptions: List[Misconception] = field(default_factory=list)
    suggested_actions: List[str] = field(default_factory=list)
    confidence: float = 1.0
    metadata: Dict[str, Any] = field(default_factory=dict) 